# Generated by Django 3.2.6 on 2021-11-27 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('email', models.EmailField(max_length=3000)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(upload_to='supplierImage/')),
                ('id_proof', models.ImageField(upload_to='supplier-id/')),
                ('address', models.TextField(blank=True, null=True)),
                ('acitve', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('experience', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_link', models.URLField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('meal_type', models.CharField(blank=True, choices=[('Veg', 'VEG'), ('Non-veg', 'NONVEG')], default='', max_length=200, null=True)),
                ('meal_feature', models.TextField(blank=True, null=True)),
                ('meal_special', models.TextField(blank=True, null=True)),
                ('mess_availability', models.CharField(blank=True, max_length=10000, null=True)),
                ('price_per_tiffin', models.IntegerField(default=0)),
                ('price_per_month', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('email', models.EmailField(max_length=3000)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(upload_to='customerImage/')),
                ('id_proof', models.ImageField(upload_to='customer-id/')),
                ('address', models.TextField(blank=True, null=True)),
                ('acitve', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
