# Generated by Django 3.2.6 on 2021-11-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0002_customer_messdetails_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdetails',
            name='mess_image1',
            field=models.ImageField(null=True, upload_to='messImage/'),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='mess_image2',
            field=models.ImageField(null=True, upload_to='messImage/'),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='mess_image3',
            field=models.ImageField(null=True, upload_to='messImage/'),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='mess_image4',
            field=models.ImageField(null=True, upload_to='messImage/'),
        ),
        migrations.CreateModel(
            name='MessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50000, null=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.messdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messApp.customer')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messApp.supplier')),
            ],
        ),
    ]
