# Generated by Django 3.2.6 on 2021-11-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0003_auto_20211127_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MessBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.IntegerField(default=0)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.customer')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.messdetails')),
            ],
        ),
    ]
