# Generated by Django 3.2.6 on 2021-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0004_contactme_messbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messbooking',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
