# Generated by Django 3.2.6 on 2021-12-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0005_auto_20211202_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='acitve',
            new_name='active',
        ),
    ]
