# Generated by Django 3.2.6 on 2021-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0006_rename_acitve_supplier_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
