# Generated by Django 3.2.6 on 2021-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0008_auto_20211211_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdetails',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='messdetails',
            name='meal_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
