# Generated by Django 3.2.6 on 2021-12-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0010_auto_20211212_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RemindMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.customer')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.messdetails')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.state')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messApp.state')),
            ],
        ),
    ]
