# Generated by Django 3.2.6 on 2021-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0011_city_district_remindme_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='messbooking',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
