# Generated by Django 3.2.6 on 2021-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0013_alter_messbooking_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messbooking',
            name='label',
            field=models.CharField(blank=True, default='panding', max_length=100, null=True),
        ),
    ]
