# Generated by Django 3.2.6 on 2021-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messApp', '0014_alter_messbooking_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='label',
            field=models.CharField(blank=True, default='panding', max_length=500, null=True),
        ),
    ]
